In [20]:
import numpy as np
import pandas as pd
from scipy.stats import binom_test, binned_statistic_2d, chisquare

In [6]:
print(binom_test(67,100,0.75,alternative='two-sided'))

0.08222258891386608


In [7]:
print(binom_test(22,50,0.75,alternative='two-sided'))

3.4831478978300243e-06


In [9]:
df = pd.read_csv('pines.txt', delimiter = '\t')
df.head()

sn    we
0  200.0   8.8
1  199.3  10.0
2  193.6  22.4
3  167.7  35.6
4  183.9  45.4

In [19]:
import scipy
print(scipy.stats.binned_statistic_2d(df['sn'], df['we'], None, 'count', bins=(5,5)).statistic)
x = scipy.stats.binned_statistic_2d(df['sn'], df['we'], None, 'count', bins=(5,5)).statistic
avg= sum([sum(a) for a in x])/x.size
avg

[[18. 26. 29. 25. 20.]
 [14. 12. 22. 34. 25.]
 [12. 24. 15. 50. 37.]
 [ 8. 19. 31. 50.  7.]
 [ 7.  8. 37. 27. 27.]]


23.36

In [24]:
print(chisquare(x.reshape(25), np.ones((25))*23.36).statistic)

150.58904109589042
